const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root=path.resolve(__dirname,'../../web/static');
(async()=>{const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');return res.end('<div id="box"></div><div id="hand"></div>')};const file=path.join(root,req.url);if(!file.startsWith(root)){res.statusCode=403;return res.end()};res.setHeader('Content-Type','text/javascript');try{res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({...(process.platform==='win32'?{channel:'msedge'}:{}),headless:true,args:['--no-sandbox']});try{
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
const fields=[{name:'slot',type:'moorNumber',min:1,max:3},{name:'mode',type:'moorAgeOrder',min:1,max:1},{name:'specialWorker',type:'moorTraining',min:1,max:1,options:[{id:'regular',label:'普通工人'},{id:'chef',label:'主厨'}]},{name:'cardIds',type:'moorPrivateCards',min:1,max:1},{name:'field',type:'moorAnyField',min:1,max:1},{name:'opponentField',type:'moorOpponentField',min:1,max:1},{name:'seats',type:'moorSeats',min:2,max:2,options:[{space:'tour',slot:1,label:'导览'},{space:'draw_vine',slot:2,label:'抽藤'}]},{name:'colors',type:'moorDrawColors',min:3,max:3},{name:'buildings',type:'moorBuildings',min:3,max:3,discount:99}];
const report=[];
for(const f of fields){await page.evaluate(async f=>{const {renderVisitor}=await import('/js/visitor-ui.js');const p={id:'p',name:'测试玩家',coins:50,vp:10,workers:2,largeWorker:true,totalWorkers:3,income:2,wines:[],grapes:[],buildings:[],fields:[{index:0,capacity:5,sold:false,vines:[{red:1}],harvested:false}],structureSlots:[]};const c={id:f.type,kind:'visitor',playerId:'p',options:['go'],labels:{go:'执行'},optionFields:{go:[f]},visitor:{cardId:'moor-summer-15',stage:'private',actorId:'p'},cards:[{id:'private-order',type:'order',name:'私密订单',description:'仅当前响应者可见'}],title:'Moor 测试',description:'卡面说明'};const v={code:f.type,youId:'p',phase:'summer',revision:1,year:1,players:[p,{...p,id:'q',name:'邻座'}],hand:[],spaces:[],config:{board:'ee',visitors:'ee_moor'},pendingChoice:c,optionReasons:{}};window.sent=null;renderVisitor(document.querySelector('#box'),v,async a=>{window.sent=a;return true},true)},f);
assert.equal(await page.locator('select').count(),0,f.type+' should use cards');assert.equal(await page.locator('text=尚未支持的界面字段').count(),0,f.type);
if(f.type==='moorPrivateCards')await page.locator('[data-value="private-order"]').click();if(f.type==='moorSeats'){await page.locator('[data-value="0"]').click();await page.locator('[data-value="1"]').click()};if(f.type==='moorBuildings'){for(const id of ['medium_cellar','large_cellar','yoke'])await page.locator('[data-value="'+id+'"]').click()};
assert.equal(await page.locator('[data-visitor-submit]').isDisabled(),false,f.type+' not ready');await page.locator('[data-visitor-submit]').click();const sent=await page.evaluate(()=>window.sent);assert(sent,f.type);if(f.type==='moorNumber')assert.equal(sent.slot,1);if(f.type==='moorPrivateCards')assert.deepEqual(sent.cardIds,['private-order']);if(f.type==='moorOpponentField')assert.deepEqual(sent.targetIds,['q']);if(f.type==='moorSeats')assert.deepEqual(sent.targetIds,['tour','draw_vine']);if(f.type==='moorDrawColors')assert.deepEqual(sent.colors,['vine','vine','vine']);if(f.type==='moorBuildings')assert.deepEqual(sent.buildings,['medium_cellar','large_cellar','yoke']);report.push({type:f.type,payload:sent});
}
const gating=await page.evaluate(async()=>{const {cardMatchesSeason,renderMoorField}=await import('/js/moor-ui.js');return ['ee','rhine'].every(visitors=>!cardMatchesSeason({id:'moor-winter-10',type:'winter'},'summer',{visitors})&&!renderMoorField({type:'moorNumber'},{v:{config:{visitors}}}))});assert(gating,'unselected visitors must not expose Moor controls');
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:report.length,report}));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}})().catch(e=>{console.error(e);process.exitCode=1});
