import {localCard} from './card-i18n.js';
import {renderEE, cardArt, setupEE} from './ee-ui.js';
import {art, worker, decorateTable, renderEstate, actionArt} from './graphics.js';
const $=s=>document.querySelector(s);
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e};
const types={vine:'葡萄藤',order:'订单',summer:'夏季访客',winter:'冬季访客',red:'红',white:'白',blush:'桃红',sparkling:'起泡'};
const buildings={trellis:'棚架 · 2金币',irrigation:'灌溉 · 3金币',medium_cellar:'中酒窖 · 4金币',large_cellar:'大酒窖 · 6金币',cottage:'小屋 · 4金币',windmill:'磨坊 · 5金币',tasting_room:'品酒室 · 6金币',yoke:'轭 · 2金币'};
const phases={setup:'开局 · 家族传承',fall:'秋季 · 访客到来',year_end:'年末 · 整理手牌',lobby:'好友集结',wake:'春日 · 起床顺序',summer:'夏季 · 葡萄园',winter:'冬季 · 酿酒坊',finished:'收官 · 年度佳酿'};
let token=localStorage.getItem('vineyard-ee-token')||'',state=null,source=null,selected=null,busy=false,online=false;
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500)}
async function api(path,body){const opts={headers:{}};if(body!==undefined){opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body)}if(token)opts.headers.Authorization='Bearer '+token;const r=await fetch(path,opts);const data=await r.json();if(!r.ok)throw new Error(data.error||'请求失败');return data}
function setConnection(text){$('#connection').textContent=text}
function cardText(original){const c=localCard(original);let t=c.name+' / '+c.englishName;if(c.type==='vine')t+=` / 红${c.red} 白${c.white}`;if(c.type==='order')t+=' / '+(c.requirements||[]).map(w=>`${types[w.type]}酒≥${w.value}`).join(' + ')+` → ${c.points}分`;return t}
function myPlayer(){return state.players.find(p=>p.id===state.youId)}
function playerName(id){return state.players.find(p=>p.id===id)?.name||'—'}
function render(v){const focusedCard=document.activeElement?.dataset.cardId;for(const s of v.spaces||[])s.occupied??=[];for(const p of v.players||[]){p.buildings??=[];p.grapes??=[];p.wines??=[];p.fields??=[];for(const f of p.fields)f.vines??=[]}state=v;decorateTable(v);$('#welcome').hidden=true;$('#game').hidden=false;$('#season-title').textContent=(v.phase==='lobby'?'':`第 ${v.year} 年 · `)+phases[v.phase];$('#code-label').textContent='房间 '+v.code;$('#turn-label').textContent=v.phase==='finished'?'最高排名：'+playerName(v.winnerId):v.turnId?(v.turnId===v.youId?'轮到你行动':'等待 '+playerName(v.turnId)+' 行动'):'房主：'+playerName(v.hostId);$('#status').textContent=v.turnId===v.youId?'轮到你了。选择行动，或结束本季保留工人进入下一季。':v.phase==='lobby'?'分享局域网地址和房间码，等待好友加入。':'';$('#lobby-panel').hidden=v.phase!=='lobby';$('#start-game').disabled=!v.legal.canStart||!online;$('#wake-panel').hidden=v.phase!=='wake';$('#board').hidden=!['summer','winter'].includes(v.phase);$('#pass').disabled=!v.legal.canPass||!online;$('#hand-panel').hidden=v.phase==='lobby';
 const wake=$('#wake-options');wake.replaceChildren();for(const s of v.wakeSlots||[]){const b=el('button');b.append(el('strong',s.slot),el('span',s.bonus),el('span',s.playerId?playerName(s.playerId):'选择'));b.disabled=!!s.playerId||!v.legal.canWake||!online;if(s.playerId)b.prepend(worker(v,s.playerId,false));b.dataset.slot=s.slot;b.onclick=()=>s.slot===5?setupEE('wake',state,act):act({type:'wake',slot:s.slot});wake.append(b)}
 const board=$('#spaces');board.replaceChildren();for(const s of v.spaces||[]){if(s.season!==v.phase&&s.season!=='any')continue;const b=el('button',null,'space');b.dataset.space=s.id;b.append(art(actionArt[s.id]||'estate','action-art'));b.append(el('strong',s.name),el('span',s.description,'desc'));const seats=el('div',null,'worker-slots');for(let i=0;i<Math.min(6,Math.max(s.capacity>6?0:s.capacity,s.occupied.length));i++){const seat=el('span',null,'worker-slot'+(i>=s.capacity?' overflow-seat':''));const o=s.occupied[i];if(o){seat.append(worker(v,o.playerId,o.large));seat.title=playerName(o.playerId)+(o.large?' · 大工人':' · 普通工人');seat.setAttribute('aria-label',seat.title)}else{seat.textContent='空';seat.setAttribute('aria-label','空闲普通行动格')}seats.append(seat)}b.append(seats);const normal=Math.min(s.occupied.length,s.capacity);b.append(el('span',`普通格 ${normal}/${s.capacity} · 大工人可突破占位`,'slots'));if(s.occupied.length)b.append(el('small',s.occupied.map(o=>playerName(o.playerId)+(o.large?'（大）':'')).join('、')));b.disabled=!v.legal.canPlace||!online||!!s.disabledReason;if(s.disabledReason)b.append(el('small','访客效果尚未完成 · 不以演示效果替代','ee-warning'));b.onclick=()=>openAction(s);board.append(b)}
 const hand=$('#hand');hand.replaceChildren();for(const original of v.hand||[]){const c=localCard(original);const e=el('article',null,'card '+c.type);e.dataset.cardId=c.id;e.append(cardArt(c,'card-art'));e.append(el('span',types[c.type]||c.type,'type'),el('h4',c.name),el('small',c.englishName,'card-english'),el('p',c.description));if(c.type==='vine')e.append(el('b',`红 ${c.red} · 白 ${c.white}`));if(c.type==='order')e.append(el('b',(c.requirements||[]).map(w=>`${types[w.type]}酒 ≥ ${w.value}`).join(' + ')),el('p',`奖励 ${c.points}分 · 收入 +${c.income}`));if(['summer','winter'].includes(c.type)&&!c.implemented)e.append(el('small','效果尚未实现 / 不可打出','ee-warning'));hand.append(e)}if(!v.hand?.length)hand.append(el('p','暂无手牌','empty'));
 const ps=$('#players');ps.replaceChildren();for(const p of [...v.players].sort((a,b)=>(b.id===v.youId)-(a.id===v.youId)))ps.append(renderEstate(v,p,buildings,types));
 const logs=$('#log');logs.replaceChildren(...[...(v.log||[])].reverse().map(s=>el('li',s)));$('#rules-text').replaceChildren(...v.rulesNotes.map(n=>el('p',n)));renderEE(v,act,online);if(focusedCard){const card=[...hand.children].find(e=>e.dataset.cardId===focusedCard);if(card?.tabIndex===0)card.focus({preventScroll:true})}
}
async function connect(){if(!token)return;try{const v=await api('/api/state?token='+encodeURIComponent(token));online=true;render(v);source?.close();source=new EventSource('/api/events?token='+encodeURIComponent(token));source.onopen=()=>{online=true;setConnection('● 已连接本地服务器');if(state)render(state)};source.onmessage=e=>{online=true;render(JSON.parse(e.data))};source.onerror=()=>{online=false;setConnection('○ 断线，正在自动重连…');if(state)render(state)};}catch(e){online=false;setConnection('连接失败');toast(e.message)}}
async function enter(create){if(busy)return;const name=$('#nickname').value.trim(),code=$('#room-code').value.trim().toUpperCase();if(!name)return toast('请填写昵称');busy=true;try{const r=await api(create?'/api/create':'/api/join',create?{name}:{name,code});token=r.token;localStorage.setItem('vineyard-ee-token',token);localStorage.setItem('vineyard-ee-name',name);await connect()}catch(e){toast(e.message)}finally{busy=false}}
async function act(a){if(busy)return;busy=true;try{const v=await api('/api/action',{revision:state.revision,...a});render(v);return true}catch(e){toast(e.message);$('#form-error').textContent=e.message;return false}finally{busy=false}}
$('#create-room').onclick=()=>enter(true);$('#join-room').onclick=()=>enter(false);$('#start-game').onclick=()=>act({type:'start'});$('#pass').onclick=()=>{if(confirm('确定结束本季？剩余工人会保留至冬季；冬季结束后进入年末结算。'))act({type:'pass'})};$('#switch-table').onclick=()=>{if(!confirm('返回入口不会退出座位。原会话仍可刷新恢复；加入新房间会替换本浏览器保存的会话。继续？'))return;source?.close();online=false;$('#welcome').hidden=false;$('#game').hidden=true;setConnection('已返回入口')};$('#invite').onclick=async()=>{const u=new URL(location.href);u.search='room='+state.code;try{await navigator.clipboard.writeText(u.href);toast('邀请链接已复制。请确保链接中的地址是服务器局域网IP。')}catch{prompt('复制邀请链接（如为localhost，请改为服务器局域网IP）',u.href)}};
function selectField(parent,name,label,items){const l=el('label',label),s=el('select');s.name=name;s.required=true;const placeholder=el('option','请选择');placeholder.value='';s.append(placeholder);for(const [value,text]of items){const o=el('option',text);o.value=value;s.append(o)}if(name==='slot')s.value='0';l.append(s);parent.append(l)}
function checks(parent,name,label,items){parent.append(el('p',label));if(!items.length)parent.append(el('p','暂无可用资源','empty'));for(const [value,text]of items){const l=el('label',null,'check'),i=el('input');i.type='checkbox';i.name=name;i.value=value;l.append(i,document.createTextNode(text));parent.append(l)}}
function openAction(s){if(['gain_coin','yoke','plant','harvest','make_wine','sell_grapes'].includes(s.id))return setupEE(s,state,act);selected={...s,revision:state.revision};const p=myPlayer();$('#action-illustration').replaceChildren(art(actionArt[s.id]||'estate','dialog-art'));$('#action-title').textContent=s.name;$('#action-description').textContent=s.description;$('#form-error').textContent='';const f=$('#action-fields');f.replaceChildren();selectField(f,'declineBonus','行动格奖励',[['no','领取（默认）'],['yes','放弃奖励，仍执行行动']]);if(s.capacity>1&&s.capacity<6)selectField(f,'slot','行动格（第1格为奖励格）',[[0,'自动选择'],...Array.from({length:s.capacity},(_,i)=>[i+1,'第'+(i+1)+'格'+(s.occupied.some(o=>o.slot===i+1)?'（已占用）':'')])]);$('#use-large').checked=p.workers===0||s.occupied.length>=s.capacity;$('#use-large').disabled=!p.largeWorker;
 const t={plant:'vine',fill_order:'order',summer_visitor:'summer',winter_visitor:'winter'}[s.id];if(t)selectField(f,'cardId','选择手牌',state.hand.filter(c=>c.type===t&&(!['summer','winter'].includes(t)||c.implemented)).map(c=>[c.id,cardText(c)]));if(['plant','harvest'].includes(s.id))selectField(f,'field','选择田地',p.fields.map(x=>[x.index,`田地 ${x.index+1} / 容量 ${x.capacity}${x.harvested?' / 已收获':''}`]));if(s.id==='build')selectField(f,'building','选择建筑',Object.entries(buildings).filter(([id])=>!p.buildings.includes(id)));if(['make_wine','sell_grapes'].includes(s.id))checks(f,'grapes','选择葡萄（每次酿造一瓶）',p.grapes.map((g,i)=>[i,`${types[g.color]}葡萄 · 品质 ${g.value}`]));if(s.id==='fill_order')checks(f,'wineIds','选择要交付的葡萄酒',p.wines.map(w=>[w.id,`${types[w.type]}葡萄酒 · 品质 ${w.value}`]));$('#action-dialog').showModal()}
$('#close-dialog').onclick=()=>$('#action-dialog').close();$('#action-form').onsubmit=async e=>{e.preventDefault();if(!selected)return;const data=new FormData(e.target),a={type:'place',revision:selected.revision,space:selected.id,large:$('#use-large').checked,declineBonus:data.get('declineBonus')==='yes'};if(data.get('slot'))a.slot=Number(data.get('slot'));for(const key of ['cardId','building'])if(data.get(key))a[key]=data.get(key);if(data.has('field'))a.field=Number(data.get('field'));if(['make_wine','sell_grapes'].includes(selected.id))a.grapes=data.getAll('grapes').map(Number);if(selected.id==='fill_order')a.wineIds=data.getAll('wineIds');$('#confirm-action').disabled=true;try{if(await act(a))$('#action-dialog').close()}finally{$('#confirm-action').disabled=false}};
$('#nickname').value=localStorage.getItem('vineyard-ee-name')||'';const invitation=new URL(location.href).searchParams.get('room');if(invitation)$('#room-code').value=invitation.toUpperCase();if(token&&!invitation)connect();
